### ISSUE TITLE
Roadmap to first release

### ISSUE THREAD

**Issue by maltezfaria** [zmoitier/HAdaptiveIntegration.jl#2]
I am opening this issue so that we can discuss ideas and keep track of progress prior to a first release of this package. 

Here is an evolving list of things we may want to address prior to `0.1`:

- [x] Add (embedded) quadrature rules for the `Segment`.
- [x] Add (embedded) quadrature rules for the `Tetrahedron` shapes. [This paper](https://www.sciencedirect.com/science/article/pii/0377042793900279) may be a useful reference.
- [x] Add (embedded) quadrature rules for the `Square`
- [x] Add (embedded) quadrature rules for the `Cube`
- [x] Create an infrastructure automating the tests of quadrature rules and their corresponding orders
  - [x] 1-simplex
  - [x] 2-simplex
  - [x]  3-simplex
  - [x] n-simplex 
- [x] Add tests for the various quadratures used
- [x] Write a `README` and a documentation

@zmoitier Feel free to open a separate issue + PR if you feel like addressing any of the suggestions above. I can take a crack at any of them, just let me know what you prefer (and feel free to add more, these are the first ones that come to my mind right now!).
